//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        public int ClubID { get; set; }
        public string NomClub { get; set; }
        public string EmailClub { get; set; }
        public string TelClub { get; set; }
        public Nullable<int> CompetitionID { get; set; }
        public Nullable<int> MedecinID { get; set; }
        public Nullable<int> AJoueurID { get; set; }
    }
}
