//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp_Club
    {
        public int Comp_ClubID { get; set; }
        public Nullable<int> ClubID { get; set; }
        public Nullable<int> CompetitionID { get; set; }
        public Nullable<System.DateTime> DateComp_Club { get; set; }
        public Nullable<int> MedecinID { get; set; }
    }
}
