//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controle
    {
        public int ConroleID { get; set; }
        public string TextControle { get; set; }
        public string TypeControle { get; set; }
        public Nullable<int> CategorieID { get; set; }
    }
}
