//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCMA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
        public virtual DbSet<Profil> Profil { get; set; }
        public virtual DbSet<Saison> Saison { get; set; }
        public virtual DbSet<Competition> Competition { get; set; }
        public virtual DbSet<Joueur> Joueur { get; set; }
        public virtual DbSet<Club> Club { get; set; }
        public virtual DbSet<Comp_Club> Comp_Club { get; set; }
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<Dossier> Dossier { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Controle> Controle { get; set; }
        public virtual DbSet<Confirmation> Confirmation { get; set; }
        public virtual DbSet<File> File { get; set; }
    }
}
