//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCMA.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Dossier
    {
        public int DossierID { get; set; }
        public Nullable<int> JoueurID { get; set; }
        public Nullable<int> ClubID { get; set; }
        public Nullable<int> MedecinID { get; set; }
        public string DateDossier { get; set; }
        public string FileDossier { get; set; }
    }
    public partial class DossierName
    {
        public int DossierID { get; set; }
        public string NomJoueur { get; set; }
        public string NomClub { get; set; }
        public string NomUtilisateur { get; set; }
        public string Confirmation { get; set; }
        public string DateDossier { get; set; }
        public string FileDossier { get; set; }
    }

}
